version: 2

models:

  - name: stg_amazon_products

    columns:

      - name: product_id
        tests:
          - unique
          - not_null

      - name: rating
        tests:
          - not_null

  - name: stg_amazon_reviews

    columns:

      - name: review_id
        tests:
          - not_null